/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ai.datalab.designer.wiz.panels;

import java.awt.BorderLayout;
import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.event.ChangeListener;
import org.openide.WizardDescriptor;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.explorer.propertysheet.PropertySheetView;
import org.openide.nodes.Node;
import org.openide.util.HelpCtx;
import org.ai.datalab.designer.wiz.ExecutorWizardIterator;
import org.ai.datalab.visual.impl.widget.DescriptiveExecutionUnit;

/**
 *
 * @author Mohan Purushothaman
 */
public class ConfigVisualPanel extends JPanel {

    /**
     * Creates new form TypeFilterVisualPanel
     */
    public ConfigVisualPanel(ExecutorWizardIterator iterator) {
        initComponents();
        update(iterator);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public final void update(ExecutorWizardIterator iterator) {
        DescriptiveExecutionUnit selectedNode = iterator.getSelectedNode();
        removeAll();
        if (selectedNode != null) {
            PropertySheet prop = new PropertySheet();
            prop.setNodes(new Node[]{selectedNode.getNode(null)});
            add(prop, BorderLayout.CENTER);
        }
    }
}
