/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.ai.datalab.adx.java.visual.simple;

import org.ai.datalab.adx.java.JavaCodeGenerator;
import org.ai.datalab.adx.java.core.JavaExecutorProvider;
import org.ai.datalab.adx.java.core.simple.SimpleJavaCodeGenerator;
import org.ai.datalab.adx.java.util.JavaUtil;
import org.ai.datalab.adx.java.visual.DataLabClassPathProvider;
import org.ai.datalab.adx.java.visual.JavaConnectorPanel;
import org.ai.datalab.adx.java.visual.JavaVisualUtil;
import org.ai.datalab.core.Data;
import org.ai.datalab.core.Executor;
import org.ai.datalab.core.adx.CodeSegment;
import org.ai.datalab.core.executor.ExecutorType;
import org.ai.datalab.core.executor.Processor;
import org.ai.datalab.core.executor.Reader;
import org.ai.datalab.designer.panels.VisualNodeValidator;
import org.ai.datalab.visual.impl.widget.DescriptiveExecutionUnit;
import org.netbeans.api.progress.ProgressHandle;

/**
 *
 * @author Mohan Purushothaman
 */
public class SimpleJavaConnectorPanel extends VisualNodeValidator {

    private final ExecutorType type;
    private final Data sampleInput;
    private final JavaCodeGenerator codeGenerator;
    private final String className;

    public SimpleJavaConnectorPanel(SimpleJavaCodeGenerator generator, ExecutorType type, Data sampleInput) {
        this.type = type;
        this.sampleInput = sampleInput;
        this.codeGenerator = generator;
        this.className = JavaUtil.getFileName(codeGenerator.getClazzName());
        initComponents();
       
        JavaVisualUtil.initiateSimpleJavaEditor(pane, generator, className);
        DataLabClassPathProvider.updateCodeGenerator(generator);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pane = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();

        jScrollPane1.setViewportView(pane);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(SimpleJavaConnectorPanel.class, "SimpleJavaConnectorPanel.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public String prepareValidation() {
        return "Validating Simple Java Connector";
    }

    @Override
    public DescriptiveExecutionUnit validateConnector(ProgressHandle handle) throws Exception {

        codeGenerator.getCodeSegmentHandler().setCodeSegment(CodeSegment.EXECUTE, pane.getText());

        Class<Executor> clazz = JavaUtil.createClass(codeGenerator.getClazzName(), codeGenerator.generate(), codeGenerator.getLibList());
        Executor e = clazz.newInstance();
        Data sampleOutput = getSampleData(e);
        JavaExecutorProvider javaExecutorProvider = new JavaExecutorProvider(type, codeGenerator, sampleOutput == null ? null : JavaConnectorPanel.getDummyMapping(sampleOutput));

        return new SimpleJavaExecutionUnit("simple java " + type.name().toLowerCase(), javaExecutorProvider, sampleInput);
    }

    @Override
    public void finishValidation() {

    }

    private Data getSampleData(Executor e) throws Exception {

        switch (type) {
            case READER:
                return ((Reader) e).readData(null);
            case PROCESSOR:
                return ((Processor) e).processData(new Data[]{sampleInput}, null)[0];
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JEditorPane pane;
    // End of variables declaration//GEN-END:variables
}
